### ISSUE TITLE
More business case examples

### ISSUE THREAD

**Issue by engelhuber** [fiskaltrust/middleware-demo-postman#3]
It would be very helpful to have more business case examples e.g.:
- Till starting
- Till closing (+ cash to the bank)
- manual cash in / out transfers
- ...

many thanks!

**Comment by Solrosy** [comment]
yes, please. I need this also...
![image](https://user-images.githubusercontent.com/60941951/91539349-75523f00-e919-11ea-86ee-16457b92e3f2.png)

**Comment by engelhuber** [comment]
any news?

**Comment by MarkusEGruber** [comment]
Hi, we are currently working on updating our postman collection. Once we are finished, we are publishing it here of course.

**Comment by engelhuber** [comment]
sorry to bother you again, but whats the status?

**Comment by TSchmiedlechner** [comment]
Hi everyone, sorry that we've missed to get back to you. I hope you were helped elsewhere meanwhile, but for future reference: 
Since this issue was posted, we have extended our sample collection (e.g. for [cash-pay in and pay-out](https://middleware-samples.docs.fiskaltrust.cloud/#22e9fac9-2514-4675-9281-49f779546dac)), and updated the docs to contain more information about these previously non-described cases.
